# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_referencer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblepassage',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='biblepassage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
