# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_referencer', '0002_auto_20181127_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossreference',
            old_name='source',
            new_name='sources',
        ),
    ]
