# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiblePassage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30)),
                ('first_seen', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('first_seen', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('classification', models.CharField(max_length=100)),
                ('explaination', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('destination', models.ManyToManyField(related_name='destination', to='cross_referencer.BiblePassage')),
                ('start', models.ManyToManyField(related_name='start', to='cross_referencer.BiblePassage')),
            ],
        ),
    ]
