# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_referencer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crossreference',
            old_name='explaination',
            new_name='explanation',
        ),
    ]
