# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_referencer', '0003_auto_20181127_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblepassage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
